version: "3.8"
services:
  gateway:
    container_name: "gateway"
    build:
      dockerfile: ./gateway/Dockerfile
      context: ./packages
    ports:
      - 4000:4000

  category:
    container_name: "category-service"
    build: ./packages/category

  post:
    container_name: "post-service"
    build: ./packages/post

  user:
    container_name: "user-service"
    build: ./packages/user
