import { parse } from "@microframework/parser"

describe("parse models > different model app", () => {
  test("model with different types in", () => {
    const result = parse(__dirname + "/different-models-app.ts")
    // console.log(JSON.stringify(result, undefined, 2))

    expect(result).toEqual({
      "@type": "ApplicationTypeMetadata",
      name: "App",
      description: "",
      actions: [],
      models: [
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "name",
              args: {
                "@type": "TypeMetadata",
                kind: "object",
                array: false,
                nullable: false,
                deprecated: false,
                description: "",
                canBeUndefined: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    kind: "string",
                    array: false,
                    nullable: false,
                    deprecated: false,
                    description: "",
                    canBeUndefined: false,
                    properties: [],
                    propertyName: "keyword",
                  },
                ],
              },
            },
          ],
          modelName: "PostTypeModel",
          description: "Type for a PostTypeModel.",
        },
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "name",
            },
          ],
          typeName: "PostClass",
          modelName: "PostClassModel",
          description: "Class for a PostClassModel.",
        },
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "name",
            },
          ],
          typeName: "PostInterface",
          modelName: "PostInterfaceModel",
          description: "Interface for a PostModel.",
        },
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              properties: [],
              propertyName: "name",
              args: {
                "@type": "TypeMetadata",
                kind: "object",
                array: false,
                nullable: false,
                deprecated: false,
                description: "",
                canBeUndefined: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    kind: "string",
                    array: false,
                    nullable: false,
                    deprecated: false,
                    description: "",
                    canBeUndefined: false,
                    properties: [],
                    propertyName: "keyword",
                  },
                ],
              },
            },
          ],
          modelName: "PostLiteralModel",
          description: "",
        },
      ],
      inputs: [],
      queries: [],
      mutations: [],
      subscriptions: [],
    })
  })
})
