import { parse } from "@microframework/parser"

describe("parse inputs > intersection type app", () => {
  test("input defined as a intersection type", () => {
    const result = parse(__dirname + "/intersection-type-app.ts")
    // console.log(JSON.stringify(result, undefined, 2))
    expect(result).toEqual({
      "@type": "ApplicationTypeMetadata",
      name: "App",
      description: "",
      actions: [],
      models: [
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          args: [],
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "id",
              propertyPath: "PostType.id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "name",
              propertyPath: "PostType.name",
            },
          ],
          modelName: "PostModel",
          propertyName: "PostType",
          propertyPath: "PostType",
          typeName: "PostType",
          description: "Type for a PostModel.",
        },
      ],
      inputs: [
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          args: [],
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "id",
              propertyPath: "PersonIntersectionInputType.id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "name",
              propertyPath: "PersonIntersectionInputType.name",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "aboutMe",
              propertyPath: "PersonIntersectionInputType.aboutMe",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "photoUrl",
              propertyPath: "PersonIntersectionInputType.photoUrl",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "degree",
              propertyPath: "PersonIntersectionInputType.degree",
            },
            {
              "@type": "TypeMetadata",
              kind: "boolean",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "graduated",
              propertyPath: "PersonIntersectionInputType.graduated",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "workingPlace",
              propertyPath: "PersonIntersectionInputType.workingPlace",
            },
            {
              "@type": "TypeMetadata",
              kind: "boolean",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "seekingForJob",
              propertyPath: "PersonIntersectionInputType.seekingForJob",
            },
            {
              "@type": "TypeMetadata",
              kind: "boolean",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "english",
              propertyPath: "PersonIntersectionInputType.english",
            },
            {
              "@type": "TypeMetadata",
              kind: "boolean",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "tajik",
              propertyPath: "PersonIntersectionInputType.tajik",
            },
          ],
          typeName: "PersonIntersectionInputType",
          propertyName: "PersonIntersectionInputType",
          propertyPath: "PersonIntersectionInputType",
          description: "This way we are testing intersection type.",
        },
      ],
      queries: [],
      mutations: [],
      subscriptions: [],
    })
  })
})
