import { parse } from "@microframework/parser"

describe("parse models > literal type app", () => {
  test("model with literal type", () => {
    const result = parse(__dirname + "/literal-type-app.ts")
    // console.log(JSON.stringify(result, undefined, 2))
    expect(result).toEqual({
      "@type": "ApplicationTypeMetadata",
      name: "App",
      description: "",
      actions: [],
      models: [
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          args: [],
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "id",
              propertyPath: "AlbumType.id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "name",
              propertyPath: "AlbumType.name",
            },
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: true,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "stars",
              propertyPath: "AlbumType.stars",
            },
            {
              "@type": "TypeMetadata",
              kind: "reference",
              array: false,
              nullable: false,
              deprecated: false,
              canBeUndefined: false,
              args: [],
              properties: [],
              typeName: "AlbumStatusType",
              description: "",
              propertyName: "status",
              propertyPath: "AlbumType.status",
            },
          ],
          typeName: "AlbumType",
          propertyName: "AlbumType",
          propertyPath: "AlbumType",
          description: "This way we are testing type support.",
        },
        {
          "@type": "TypeMetadata",
          kind: "enum",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          args: [],
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "property",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "active",
              propertyPath: "AlbumStatusType.active",
            },
            {
              "@type": "TypeMetadata",
              kind: "property",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "inactive",
              propertyPath: "AlbumStatusType.inactive",
            },
          ],
          typeName: "AlbumStatusType",
          propertyName: "AlbumStatusType",
          propertyPath: "AlbumStatusType",
          description: "This way we are testing type support.",
        },
      ],
      inputs: [],
      queries: [],
      mutations: [],
      subscriptions: [],
    })
  })
})
