import { parse } from "@microframework/parser"

describe("parser > parse actions", () => {
  test("actions defined with an intersections", () => {
    const appMetadata = parse(__dirname + "/intersections-app.ts")
    expect(appMetadata).toEqual({
      "@type": "ApplicationTypeMetadata",
      actions: [
        {
          "@type": "ActionTypeMetadata",
          description: "Loads a single category by its id.",
          name: "GET /api/category/:id",
          params: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category id.",
                kind: "number",
                nullable: false,
                properties: [],
                propertyName: "id",
                propertyPath: "GET /api/category/:id.params.id",
              },
            ],
            propertyName: "params",
            propertyPath: "GET /api/category/:id.params",
          },
          return: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category id.",
                kind: "number",
                nullable: false,
                properties: [],
                propertyName: "id",
                propertyPath: "GET /api/category/:id.return.id",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category name.",
                kind: "string",
                nullable: true,
                properties: [],
                propertyName: "name",
                propertyPath: "GET /api/category/:id.return.name",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: true,
                canBeUndefined: true,
                deprecated: true,
                description: "Category posts.",
                kind: "object",
                nullable: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Unique post id.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "id",
                    propertyPath: "GET /api/category/:id.return.posts.id",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Post title.",
                    kind: "string",
                    nullable: false,
                    properties: [],
                    propertyName: "title",
                    propertyPath: "GET /api/category/:id.return.posts.title",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: "Will be removed.",
                    description: "Post categories count.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "categoryCount",
                    propertyPath:
                      "GET /api/category/:id.return.posts.categoryCount",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Indicates if post is moderated or not.",
                    kind: "enum",
                    nullable: false,
                    properties: [
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post was moderated.",
                        kind: "object",
                        nullable: false,
                        properties: [],
                        propertyName: "moderated",
                        propertyPath:
                          "GET /api/category/:id.return.posts.status.moderated",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post is under moderation.",
                        kind: "object",
                        nullable: false,
                        properties: [],
                        propertyName: "under_moderation",
                        propertyPath:
                          "GET /api/category/:id.return.posts.status.under_moderation",
                      },
                    ],
                    propertyName: "status",
                    propertyPath: "GET /api/category/:id.return.posts.status",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Indicates if post is watched.",
                    kind: "boolean",
                    nullable: false,
                    properties: [],
                    propertyName: "watched",
                    propertyPath: "GET /api/category/:id.return.posts.watched",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Post watches count.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "watchesCount",
                    propertyPath:
                      "GET /api/category/:id.return.posts.watchesCount",
                  },
                ],
                propertyName: "posts",
                propertyPath: "GET /api/category/:id.return.posts",
              },
            ],
            propertyName: "",
            propertyPath: "GET /api/category/:id.return",
          },
        },
        {
          "@type": "ActionTypeMetadata",
          description:
            "Loads a single category and a single post by their ids.",
          name: "GET /api/category-post/:id",
          params: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category id.",
                kind: "object",
                nullable: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "postId",
                    propertyPath:
                      "GET /api/category-post/:id.params.args.postId",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "categoryId",
                    propertyPath:
                      "GET /api/category-post/:id.params.args.categoryId",
                  },
                ],
                propertyName: "args",
                propertyPath: "GET /api/category-post/:id.params.args",
              },
            ],
            propertyName: "params",
            propertyPath: "GET /api/category-post/:id.params",
          },
          return: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "",
                kind: "object",
                nullable: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Category id.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "id",
                    propertyPath:
                      "GET /api/category-post/:id.return.category.id",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Category name.",
                    kind: "string",
                    nullable: true,
                    properties: [],
                    propertyName: "name",
                    propertyPath:
                      "GET /api/category-post/:id.return.category.name",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: true,
                    canBeUndefined: true,
                    deprecated: true,
                    description: "Category posts.",
                    kind: "object",
                    nullable: false,
                    properties: [
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Unique post id.",
                        kind: "number",
                        nullable: false,
                        properties: [],
                        propertyName: "id",
                        propertyPath:
                          "GET /api/category-post/:id.return.category.posts.id",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Post title.",
                        kind: "string",
                        nullable: false,
                        properties: [],
                        propertyName: "title",
                        propertyPath:
                          "GET /api/category-post/:id.return.category.posts.title",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: "Will be removed.",
                        description: "Post categories count.",
                        kind: "number",
                        nullable: false,
                        properties: [],
                        propertyName: "categoryCount",
                        propertyPath:
                          "GET /api/category-post/:id.return.category.posts.categoryCount",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post is moderated or not.",
                        kind: "enum",
                        nullable: false,
                        properties: [
                          {
                            "@type": "TypeMetadata",
                            args: [],
                            array: false,
                            canBeUndefined: false,
                            deprecated: false,
                            description: "Indicates if post was moderated.",
                            kind: "object",
                            nullable: false,
                            properties: [],
                            propertyName: "moderated",
                            propertyPath:
                              "GET /api/category-post/:id.return.category.posts.status.moderated",
                          },
                          {
                            "@type": "TypeMetadata",
                            args: [],
                            array: false,
                            canBeUndefined: false,
                            deprecated: false,
                            description:
                              "Indicates if post is under moderation.",
                            kind: "object",
                            nullable: false,
                            properties: [],
                            propertyName: "under_moderation",
                            propertyPath:
                              "GET /api/category-post/:id.return.category.posts.status.under_moderation",
                          },
                        ],
                        propertyName: "status",
                        propertyPath:
                          "GET /api/category-post/:id.return.category.posts.status",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post is watched.",
                        kind: "boolean",
                        nullable: false,
                        properties: [],
                        propertyName: "watched",
                        propertyPath:
                          "GET /api/category-post/:id.return.category.posts.watched",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Post watches count.",
                        kind: "number",
                        nullable: false,
                        properties: [],
                        propertyName: "watchesCount",
                        propertyPath:
                          "GET /api/category-post/:id.return.category.posts.watchesCount",
                      },
                    ],
                    propertyName: "posts",
                    propertyPath:
                      "GET /api/category-post/:id.return.category.posts",
                  },
                ],
                propertyName: "category",
                propertyPath: "GET /api/category-post/:id.return.category",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "",
                kind: "object",
                nullable: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Unique post id.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "id",
                    propertyPath: "GET /api/category-post/:id.return.post.id",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Post title.",
                    kind: "string",
                    nullable: false,
                    properties: [],
                    propertyName: "title",
                    propertyPath:
                      "GET /api/category-post/:id.return.post.title",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: "Will be removed.",
                    description: "Post categories count.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "categoryCount",
                    propertyPath:
                      "GET /api/category-post/:id.return.post.categoryCount",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Indicates if post is moderated or not.",
                    kind: "enum",
                    nullable: false,
                    properties: [
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post was moderated.",
                        kind: "object",
                        nullable: false,
                        properties: [],
                        propertyName: "moderated",
                        propertyPath:
                          "GET /api/category-post/:id.return.post.status.moderated",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post is under moderation.",
                        kind: "object",
                        nullable: false,
                        properties: [],
                        propertyName: "under_moderation",
                        propertyPath:
                          "GET /api/category-post/:id.return.post.status.under_moderation",
                      },
                    ],
                    propertyName: "status",
                    propertyPath:
                      "GET /api/category-post/:id.return.post.status",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Indicates if post is watched.",
                    kind: "boolean",
                    nullable: false,
                    properties: [],
                    propertyName: "watched",
                    propertyPath:
                      "GET /api/category-post/:id.return.post.watched",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Post watches count.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "watchesCount",
                    propertyPath:
                      "GET /api/category-post/:id.return.post.watchesCount",
                  },
                ],
                propertyName: "post",
                propertyPath: "GET /api/category-post/:id.return.post",
              },
            ],
            propertyName: "",
            propertyPath: "GET /api/category-post/:id.return",
          },
        },
        {
          "@type": "ActionTypeMetadata",
          body: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: true,
                deprecated: false,
                description: "Category id.",
                kind: "number",
                nullable: true,
                properties: [],
                propertyName: "id",
                propertyPath: "POST /api/category.body.id",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: true,
                deprecated: false,
                description: "Category name.",
                kind: "string",
                nullable: false,
                properties: [],
                propertyName: "name",
                propertyPath: "POST /api/category.body.name",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: true,
                deprecated: false,
                description: "Indicates if category is active.",
                kind: "boolean",
                nullable: false,
                properties: [],
                propertyName: "active",
                propertyPath: "POST /api/category.body.active",
              },
            ],
            propertyName: "body",
            propertyPath: "POST /api/category.body",
          },
          description: "Saves a category.",
          name: "POST /api/category",
          return: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category id.",
                kind: "number",
                nullable: false,
                properties: [],
                propertyName: "id",
                propertyPath: "POST /api/category.return.id",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category name.",
                kind: "string",
                nullable: true,
                properties: [],
                propertyName: "name",
                propertyPath: "POST /api/category.return.name",
              },
              {
                "@type": "TypeMetadata",
                args: [],
                array: true,
                canBeUndefined: true,
                deprecated: true,
                description: "Category posts.",
                kind: "object",
                nullable: false,
                properties: [
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Unique post id.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "id",
                    propertyPath: "POST /api/category.return.posts.id",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Post title.",
                    kind: "string",
                    nullable: false,
                    properties: [],
                    propertyName: "title",
                    propertyPath: "POST /api/category.return.posts.title",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: "Will be removed.",
                    description: "Post categories count.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "categoryCount",
                    propertyPath:
                      "POST /api/category.return.posts.categoryCount",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Indicates if post is moderated or not.",
                    kind: "enum",
                    nullable: false,
                    properties: [
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post was moderated.",
                        kind: "object",
                        nullable: false,
                        properties: [],
                        propertyName: "moderated",
                        propertyPath:
                          "POST /api/category.return.posts.status.moderated",
                      },
                      {
                        "@type": "TypeMetadata",
                        args: [],
                        array: false,
                        canBeUndefined: false,
                        deprecated: false,
                        description: "Indicates if post is under moderation.",
                        kind: "object",
                        nullable: false,
                        properties: [],
                        propertyName: "under_moderation",
                        propertyPath:
                          "POST /api/category.return.posts.status.under_moderation",
                      },
                    ],
                    propertyName: "status",
                    propertyPath: "POST /api/category.return.posts.status",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Indicates if post is watched.",
                    kind: "boolean",
                    nullable: false,
                    properties: [],
                    propertyName: "watched",
                    propertyPath: "POST /api/category.return.posts.watched",
                  },
                  {
                    "@type": "TypeMetadata",
                    args: [],
                    array: false,
                    canBeUndefined: false,
                    deprecated: false,
                    description: "Post watches count.",
                    kind: "number",
                    nullable: false,
                    properties: [],
                    propertyName: "watchesCount",
                    propertyPath:
                      "POST /api/category.return.posts.watchesCount",
                  },
                ],
                propertyName: "posts",
                propertyPath: "POST /api/category.return.posts",
              },
            ],
            propertyName: "",
            propertyPath: "POST /api/category.return",
          },
        },
        {
          "@type": "ActionTypeMetadata",
          description: "Removes a category.",
          name: "DELETE /api/category/:id",
          params: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "Category id.",
                kind: "number",
                nullable: false,
                properties: [],
                propertyName: "id",
                propertyPath: "DELETE /api/category/:id.params.id",
              },
            ],
            propertyName: "params",
            propertyPath: "DELETE /api/category/:id.params",
          },
          return: {
            "@type": "TypeMetadata",
            args: [],
            array: false,
            canBeUndefined: false,
            deprecated: false,
            description: "",
            kind: "object",
            nullable: false,
            properties: [
              {
                "@type": "TypeMetadata",
                args: [],
                array: false,
                canBeUndefined: false,
                deprecated: false,
                description: "",
                kind: "boolean",
                nullable: false,
                properties: [],
                propertyName: "success",
                propertyPath: "DELETE /api/category/:id.return.success",
              },
            ],
            propertyName: "",
            propertyPath: "DELETE /api/category/:id.return",
          },
        },
      ],
      description: "",
      inputs: [],
      models: [],
      mutations: [],
      name: "App",
      queries: [],
      subscriptions: [],
    })
  })
})
