import { parse } from "@microframework/parser"

describe("parser > parse enums", () => {
  test("input defined as a type", () => {
    const result = parse(__dirname + "/app/app.ts")
    // console.log(JSON.stringify(result, undefined, 2))
    expect(result).toEqual({
      "@type": "ApplicationTypeMetadata",
      name: "App",
      description: "",
      actions: [],
      models: [
        {
          "@type": "TypeMetadata",
          kind: "object",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          args: [],
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "number",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "id",
              propertyPath: "PostType.id",
            },
            {
              "@type": "TypeMetadata",
              kind: "string",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "name",
              propertyPath: "PostType.name",
            },
            {
              "@type": "TypeMetadata",
              kind: "reference",
              array: false,
              nullable: false,
              deprecated: false,
              canBeUndefined: false,
              args: [],
              properties: [],
              description: "",
              typeName: "PostStatusType",
              propertyPath: "PostType.status",
              propertyName: "status",
            },
          ],
          typeName: "PostType",
          propertyName: "PostType",
          propertyPath: "PostType",
          description: "Type for a PostType.",
        },
        {
          "@type": "TypeMetadata",
          kind: "enum",
          array: false,
          nullable: false,
          deprecated: false,
          canBeUndefined: false,
          args: [],
          properties: [
            {
              "@type": "TypeMetadata",
              kind: "property",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "draft",
              propertyPath: "PostStatusType.draft",
            },
            {
              "@type": "TypeMetadata",
              kind: "property",
              array: false,
              nullable: false,
              deprecated: false,
              description: "",
              canBeUndefined: false,
              args: [],
              properties: [],
              propertyName: "published",
              propertyPath: "PostStatusType.published",
            },
          ],
          typeName: "PostStatusType",
          propertyName: "PostStatusType",
          propertyPath: "PostStatusType",
          description: "Type for a PostStatus.",
        },
      ],
      inputs: [],
      queries: [],
      mutations: [],
      subscriptions: [],
    })
  })
})
